- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/events/2015-derby/index.html
- site/content/index.html
Putting this in as @damacus hasn't yet had time.
> Derby is postponed.

- site/content/_upcoming.txt
- site/content/events/2015-minneapolis/_email_organizers.txt
- site/content/events/2015-minneapolis/_email_proposals.txt
- site/content/index.html
Might as well put us on the map (since we do have a date set); updating to the 2015 emails.
> Adding Minneapolis to the map & updating emails

- site/content/events/2015-washington-dc/contact/index.html
* shows the contact list (thanks @bridgetkromhout)
* use the twitter widget that actually, y'know, shows tweets
> [dc 2015] show contacts and change twitter widget

- site/content/events/2015-washington-dc/_menu.txt
- site/content/events/2015-washington-dc/_team_local.txt
- site/content/events/2015-washington-dc/index.html
- site/content/events/2015-washington-dc/sponsor/index.html
Add some more organizers and other details about our current plans.
> Edits for DC

- site/content/events/2015-austin/_team_global.txt
- site/content/events/2015-denver/_team_global.txt
- site/content/events/2015-derby/_team_global.txt
- site/content/events/2015-ljubljana/_team_global.txt
- site/content/events/2015-minneapolis/_team_global.txt
- site/content/events/2015-paris/_team_global.txt
- site/content/events/2015-washington-dc/_team_global.txt
Adding the 2015 organizers who weren't listed.
> Updating core organizer list for 2015.

- site/content/events/2015-austin/_team_global.txt
- site/content/events/2015-denver/_team_global.txt
- site/content/events/2015-derby/_team_global.txt
- site/content/events/2015-ljubljana/_team_global.txt
- site/content/events/2015-minneapolis/_team_global.txt
- site/content/events/2015-paris/_team_global.txt
- site/content/events/2015-washington-dc/_team_global.txt
Adding core organizer who was on the mailing list but missing from website.
> Adding core organizer who was missing from website

- site/content/events/2015-paris/sponsor/index.html
This fills out the sponsorship page for the 2015 Paris event.
cc @jooooooon
> add sponsorship details

- site/content/events/2015-paris/_menu.txt
> add link to code of conduct

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/index.html
Making the front page more consistent and adding bits that cities missed (the map, etc).
> Front-page cleanup to correct missing entries.

- site/content/events/2015-washington-dc/_menu.txt
- site/content/events/2015-washington-dc/sponsor/index.html
My CSS clashed with the default CSS, leaving the sponsorship table
empty. This should fix it :)
> [dc 2015] fix sponsorship table

- site/content/events/2015-paris/propose/index.html
Should have put this up sooner. :disappointed: 
cc @jooooooon
> note CFP period

- site/content/events/2015-washington-dc/conduct/index.html
- site/content/events/2015-washington-dc/contact/index.html
- site/content/events/2015-washington-dc/index.html
- site/content/events/2015-washington-dc/location/index.html
- site/content/events/2015-washington-dc/registration/index.html
- site/content/events/2015-washington-dc/sponsor/index.html
- site/layouts/event_washington_dc.txt
* fix markdown link syntax on the sponsor page
* add a map to the location page
* change "Gold sponsors" to just "Sponsors" in the sidebar, until we
have actual sponsors to list
> [dc 2015] misc fixes

- site/content/events/2015-paris/propose/index.html
> clarify proposal criteria

- site/content/events/2015-paris/registration/index.html
*finally* :smirk: 
cc @jooooooon
> open ticket sales!

- site/content/events/2015-paris/proposals/Bizdevops – from development to the customer – how to bring all links together to an amazing chain!/index.txt
- site/content/events/2015-paris/proposals/Cognitive biases and our poor intuitions around probability/index.txt
- site/content/events/2015-paris/proposals/Configuring Riemann/index.txt
- site/content/events/2015-paris/proposals/Designing the Enterprise for Manufacturing/index.txt
- site/content/events/2015-paris/proposals/Generically specific DevOps - How to support teams with different challenges adopt a standard DevOps approach/index.txt
- site/content/events/2015-paris/proposals/Making the Elephant dance – Daily deliveries at SAP/index.txt
- site/content/events/2015-paris/proposals/Pragmatic Cloud Security: What InfoSec Practitioners Have Been Waiting For/index.txt
- site/content/events/2015-paris/proposals/Show me the Metrics/index.txt
- site/content/events/2015-paris/proposals/TSDB - TSP - Riemann/index.txt
- site/content/events/2015-paris/proposals/The Importance of Language/index.txt
- site/content/events/2015-paris/proposals/Time Series Metrics @ Betfair/index.txt
- site/content/events/2015-paris/proposals/devOps culture - survey kit to deliver a project to chinese users/index.txt
It seems we forgot to put the proposals on the website, so here it is :)
Please merge at your convenience.
cc @jooooooon @phrawzty
> Paris 2015 - list of received talk/ignite proposals

- site/content/events/2015-paris/propose/index.html
Because it's important to say it out loud.
cc @masterzen @jooooooon @bridgetkromhout
> add statement on equal opportunity

- site/content/events/2015-paris/propose/index.html
> add google doc for submitting proposals

- site/content/events/2015-denver/_menu.txt
- site/content/events/2015-denver/_sponsors.txt
- site/content/events/2015-denver/conduct/index.html
* Fixed template for conduct page
* Standardized the sponsorship text
* Added ticket link to main navigation
> Update Denver 2015 Event 

- site/content/events/2015-paris/index.html
- site/content/events/2015-paris/program/index.html
- site/content/events/2015-paris/propose/index.html
and some other little fixes.
cc @jooooooon @masterzen
> clarify the primary language of presentations

- site/content/events/2015-paris/proposals/Cash is from past: future of payments/index.txt
- site/content/events/2015-paris/proposals/Change management at scale: responsible agile delivery/index.txt
- site/content/events/2015-paris/proposals/Haskell all the way down/index.txt
- site/content/events/2015-paris/proposals/LeAPIng to real world:iOT!/index.txt
- site/content/events/2015-paris/proposals/Provisioning the cloud with ansible/index.txt
Here are some talks that were proposed but for which we hadn't any pages on the 2015 Paris proposals list.
cc @phrawzty @jooooooon
> Paris 2015 - add missing proposals

- site/content/events/2015-paris/proposals/A DevOps way to Security/index.txt
- site/content/events/2015-paris/proposals/Dev+Ops: when a fairy tale comes true !/index.txt
- site/content/events/2015-paris/proposals/DevOps through history (1910s - tomorrow)/index.txt
- site/content/events/2015-paris/proposals/Git-deliver/index.txt
- site/content/events/2015-paris/proposals/How a payment processing company turned into a software release factory/index.txt
- site/content/events/2015-paris/proposals/Key Factors For A Switch to DevOps/index.txt
- site/content/events/2015-paris/proposals/Network automation: your network, your rules/index.txt
- site/content/events/2015-paris/proposals/Screwing up for fun and profit/index.txt
- site/content/events/2015-paris/proposals/The Power Of Unicorns/index.txt
We received more talks lately, here are their proposals.
Please merge,
Thanks
Brice
> Paris 2015 - lots of new talk proposals

- site/content/events/2015-paris/proposals/Continuous deployment, the necessary link for true DevOps/index.txt
- site/content/events/2015-paris/proposals/DevOps, the fundamentals to accelerate application delivery/index.txt
- site/content/events/2015-paris/proposals/The importance of Why in DevOps/index.txt
- site/content/events/2015-paris/proposals/The new stubbing practices/index.txt
Please stop, I can't follow :)
Those appeared while I was doing the previous batch. This is insane.
Please merge, but expect more PR soon :)
Thanks,
Brice
> Paris 2015: more new talks (again)

- site/content/events/2015-paris/proposals/The DevOps Checklist/index.txt
- site/content/events/2015-paris/proposals/The Quest for The Golden Pipeline/index.txt
- site/content/events/2015-paris/proposals/What Happens Without Traction/index.txt
More talks.
cc @phrawzty @jooooooon 
Please merge,
Thanks!
Brice
> Paris 2015: three more proposals.

- site/content/events/2015-paris/proposals/The Chef Prince of Azure: How 10th Magnitude used Chef to flip-turn ZS Associates into Microsoft Azure Royalty/index.txt
Hi,
A new talk proposal.
Please merge as usual,
Thanks!
Brice
> Paris 2015 - add a new talk proposal

- site/content/events/2015-paris/proposals/DevOps and Agility combined with contractual requirements in large IT organisations/index.txt
- site/content/events/2015-paris/proposals/How Voyages-sncf.com implements Devops for its clients’ benefits/index.txt
And two more talks for Paris 2015.
Please merge as usual!
Many thanks!
Brice
> Paris 2015 - more talk proposals

- site/content/events/2015-minneapolis/_sponsors.txt
instead of modifying the image to have the blue border, lets add that blue border with some CSS
> use CSS to add blue border to logos

- site/content/events/2015-paris/index.html
- site/content/events/2015-paris/propose/index.html
Due to popular demand we are extending the CFP through 4 March 2015.
cc @jooooooon @masterzen
> [paris2015] extend CFP!

- site/content/events/2015-minneapolis/_team_local.txt
Getting the band back together, and adding one more!
> Updating team

- site/content/events/2015-paris/proposals/How to reconcile DevOps and ITIL/index.txt
And we have a second ignite.
cc @phrawzty 
Many thanks!
> Paris 2015 - one more ignite

- site/content/events/2015-paris/proposals/Automating the application lifecycle in the cloud, from build to deployment/index.txt
- site/content/events/2015-paris/proposals/Containers and DevOps: New Ways to Deploy and Manage Applications at Scale/index.txt
- site/content/events/2015-paris/proposals/Git-deliver/index.txt
- site/content/events/2015-paris/proposals/How to maintain your OpenStack up-to-date/index.txt
- site/content/events/2015-paris/proposals/How to make a Kick Ass Devops Meetup Group for 20 Euros/index.txt
- site/content/events/2015-paris/proposals/The road to DevOps : experience from the field/index.txt
As we approach the CfP close date (which apparently is today), we
get a bit more talks.
cc @phrawzty 
Many Thanks!
> Paris 2015 - more talks proposals

- site/content/events/2015-paris/index.html
- site/content/events/2015-paris/program/index.html
- site/content/events/2015-paris/propose/index.html
Too many good proposals - going to be hard to decide.
cc @masterzen
> [paris2015] close CFP

- site/content/events/2015-paris/proposals/DevOps Culture at BlaBlaCar - Keep CAMS and grow/index.txt
Hi,
It is the very last talk before we closed the CfP.
cc @phrawzty 
Thanks,
> The very last talk that was submitted

- site/content/events/2015-paris/proposals/Network automation: your network, your rules/index.txt
Hi,
One last minute modification to a talk proposal.
cc @phrawzty 
Thanks !
> Paris 2015 - one talk proposal modification

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/index.html
The NYC 2015 page already exists, it just needs to be linked from the main page.
> Add NYC 2015 to main page

- site/content/events/2015-ljubljana/_menu.txt
- site/content/events/2015-ljubljana/index.html
- site/content/events/2015-ljubljana/program/index.html
- site/content/events/2015-ljubljana/proposals/Does our infrastructure even exist/index.txt
- site/content/events/2015-ljubljana/proposals/Engineers hiring engineers/index.txt
Any chance we could get this one in swiftly? :)
cc @bridgetkromhout
> [ljubljana 2015] program

- site/content/events/2015-paris/program/index.html
:star2: :tada: :dancer: :heart_eyes_cat:
cc @jooooooon @masterzen
> [paris-2015] publish programme

- site/content/events/2015-paris/location/index.html
> add more location, transport, and accommodation info

- site/content/events/2015-minneapolis/proposals/Building Reactive Infrastructure with Consul/index.txt
- site/content/events/2015-minneapolis/proposals/Fear and Failure/index.txt
- site/content/events/2015-minneapolis/proposals/Managing Your Mental Stack/index.txt
- site/content/events/2015-minneapolis/proposals/Shedding the Stigmas of Golden Images/index.txt
- site/content/events/2015-minneapolis/proposals/The 10 Myths of DevOps/index.txt
- site/content/events/2015-minneapolis/proposals/The Five Love Languages of DevOps/index.txt
- site/content/events/2015-minneapolis/proposals/index.txt
- site/content/events/2015-minneapolis/propose/index.html
- site/content/events/2015-template/propose/index.html
Adding talks to MSP (and a line I forgot in the 2015 template).
> Adding talks to MSP

- site/content/events/2015-paris/proposals/Cloud & DevOps : Imagine a new world/index.txt
- site/content/events/2015-paris/proposals/What are unicorns/index.txt
As said in the subject we've accepted some more ignites.
More to come later.
Thanks!
> Paris 2015: a couple more ignites

- site/content/events/2015-minneapolis/proposals/DevOps for the Masses/index.txt
- site/content/events/2015-minneapolis/proposals/How to Hire a Good DevOps Engineer/index.txt
- site/content/events/2015-minneapolis/proposals/How to Teach DevOps with Cookies/index.txt
> Adding Speaker 4.

- site/content/_upcoming.txt
- site/content/index.html
Added Silicon Valley to the front page.
> Added Silicon Valley to the front page.

- site/content/events/2015-template/_cfp_date_announce.txt
- site/content/events/2015-template/_cfp_date_end.txt
- site/content/events/2015-template/_cfp_date_start.txt
- site/content/events/2015-template/propose/index.html
> Correcting the confusing template around CFP dates.

- site/content/events/2015-paris/program/index.html
- site/content/events/2015-paris/proposals/DevOps Culture at BlaBlaCar - Keep CAMS and grow/index.txt
> add speaker Nicolas Blanc (blablacar)

- site/content/events/2015-minneapolis/index.html
> Make "reg opening" date more accurate.

- site/content/events/2015-minneapolis/proposals/Philosophy of Configuration Management/index.txt
Adding another proposal for MSP.
> Adding another proposal for MSP.

- site/content/events/2015-paris/index.html
cc @masterzen @jooooooon 
Low priority. :small_blue_diamond:
> update sponsor info

- site/content/events/2015-minneapolis/proposals/Agent of Change/index.txt
> Adding a talk to MSP.

- site/content/events/2015-amsterdam/_menu.txt
- site/content/events/2015-amsterdam/index.html
* removes location from navbar
* fixes link to registration page
> adds register link to navbar

- site/content/events/2015-paris/_sponsors.txt
> Add missing comma - duh

- site/content/pages/organizing/01-Getting started/04-requirements.txt
Please let me know if we think this accurately communicates how we want events to handle speaker selection (specifically, the need for a public CFP).
> Clarifying the need for a public CFP.

- site/content/_upcoming.txt
- site/content/events/2015-chicago/_sponsors.txt
- site/content/events/2015-chicago/conduct/index.html
- site/content/events/2015-chicago/contact/index.html
- site/content/events/2015-chicago/index.html
- site/content/events/2015-chicago/sponsor/index.html
- site/content/index.html
This PR adds Chicago to the homepage and updates our sponsorship page.
> Chicago updates

- site/content/events/2015-washington-dc/index.html
* Add the theme:  _A house divided against itself cannot stand_
* Move the logo
* Add the tagline _Change is in session_
* Add info about registration, cfp, and sponsors
/cc @markcornick
> Updates to the DC home page

- site/content/_future.txt
> remove Derby from upcoming

- site/content/events/2015-minneapolis/_sponsors.txt
- site/content/events/2015-minneapolis/proposals/A DevOps Philosophy/index.txt
- site/content/events/2015-minneapolis/proposals/Adoption of ChatOps/index.txt
- site/content/events/2015-minneapolis/proposals/Good Bad and Ugly of devOps/index.txt
Adding three proposed talks and fixing the spelling of a sponsor name.
> New talks & typo fix - MSP.

- site/content/events/2015-minneapolis/proposals/DevOps from an investors perspective/index.txt
- site/content/events/2015-minneapolis/proposals/Insert Keynote Here/index.txt
- site/content/events/2015-minneapolis/proposals/The donkeys are coming/index.txt
Adding three more talks to MSP.
> Adding three more talks to MSP.

- site/content/events/2015-minneapolis/proposals/DevOps from an investors perspective/index.txt
- site/content/events/2015-minneapolis/proposals/Insert Keynote Here/index.txt
- site/content/events/2015-minneapolis/proposals/The donkeys are coming/index.txt
These weren't ignites. Copypasta error.
> These weren't ignites. Copypasta error.

- site/content/events/2015-minneapolis/_menu.txt
- site/content/events/2015-minneapolis/index.html
- site/content/events/2015-minneapolis/registration/index.html
> Opening registration for MSP.

- site/content/events/2015-denver/speakers/index.html
Commit says it all.
cc @tavisto.
I'll also ping Jason Hand about this change.
> Update title for my DevOps Days Rockies 2015 presentation.

- site/content/events/2015-melbourne/registration/index.html
> Adding registration for Melbourne 2015

- site/content/events/2015-newyork/_sponsors.txt
- No more platinum sponsors
- Instead of "Silver Sponsors" just "Sponsors"
> We only have one type of sponser for this event

- site/content/events/2015-paris/program/index.html
> fix program schedule

- site/content/events/2015-amsterdam/program/index.html
Hey guys,
We start working on the program. We start with the keynotes.
> draft schedule

- site/content/events/2015-minneapolis/_team_local.txt
- site/content/events/2015-minneapolis/proposals/The Hello World of DevOps/index.txt
Adding talk, removing organizer who won't have time this year.
> Adding talk, removing organizer

- site/content/events/2015-minneapolis/proposals/Building SaaS Applications on AWS/index.txt
- site/content/events/2015-minneapolis/proposals/Code like a Beginner with the Insight of a Pro/index.txt
- site/content/events/2015-minneapolis/proposals/Home is the New Dev/index.txt
- site/content/events/2015-minneapolis/proposals/Humanizing Technology/index.txt
- site/content/events/2015-minneapolis/proposals/They Dont Call it Continuous Integration for Nothing/index.txt
> Adding talks for MSP.

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Removing Ljubljana from the map and moving it to "past". 
Rearranging flags so everything in the US is readable.
> Front page cleanup.

- site/content/events/2015-pittsburgh/sponsor/index.html
> Pittsburgh 2015: Adds sponsorship prospectus link

- site/content/events/2015-minneapolis/proposals/DevOps Day 2 - People and Process/index.txt
- site/content/events/2015-minneapolis/proposals/DevOps Next Steps - Event Driven Operations /index.txt
Adding two more talks for Minneapolis.
> Adding two more talks for Minneapolis.

- site/content/events/2015-minneapolis/index.html
- site/content/events/2015-minneapolis/proposals/index.txt
Ensuring sponsors show on the MSP proposals page.
> Ensuring sponsors show on the MSP proposals page.

- site/content/events/2015-paris/program/index.html
> adjust timing; add details for evening event

- site/content/events/2015-amsterdam/_sponsors.txt
This is what it looks like before the fix.
/cc @ksatirli
> Fixes to the AMS sponsors.

- site/content/events/2015-minneapolis/_sponsors.txt
Fixing sponsor links for MSP. All-SSL only works if people have their certs right. /cc @tduffield
> Fixing sponsor links for MSP

- site/content/events/2015-paris/index.html
- site/content/events/2015-paris/registration/index.html
> Paris 2015 is sold out! woo!

- site/content/events/2015-minneapolis/proposals/Choose Boring Technology/index.txt
- site/content/events/2015-minneapolis/proposals/DevOps in IBM Power System Testing/index.txt
- site/content/events/2015-minneapolis/proposals/Enabling DevOps Through End to End Performance Monitoring/index.txt
- site/content/events/2015-minneapolis/proposals/Lets Safety Dance/index.txt
- site/content/events/2015-minneapolis/proposals/Performance Metrics Driven Continuous Delivery/index.txt
- site/content/events/2015-minneapolis/proposals/Testing in an Agile DevOps World/index.txt
- site/content/events/2015-minneapolis/proposals/We all scream for Metrics/index.txt
> Adding talks for Minneapolis.

- site/content/events/2015-newyork/program/index.html
> Fixed bolding per Katherine.

- site/content/events/2015-minneapolis/_menu.txt
- site/content/events/2015-minneapolis/index.html
- site/content/events/2015-minneapolis/proposals/Cheffing Etsy/index.txt
- site/content/events/2015-minneapolis/proposals/Effortless WebPerf Monitoring/index.txt
- site/content/events/2015-minneapolis/proposals/Vulnerability/index.txt
- site/content/events/2015-minneapolis/proposals/Why orchestration tools should understand your app/index.txt
- site/content/events/2015-minneapolis/proposals/Why you should care about DevOps in the public sector/index.txt
- site/content/events/2015-minneapolis/proposals/linux command-fu for developers/index.txt
- site/content/events/2015-minneapolis/propose/index.html
> Adding more MSP talks; closing CFP.

- site/content/events/2015-washington-dc/_menu.txt
- site/content/events/2015-washington-dc/index.html
- site/content/events/2015-washington-dc/location/index.html
* Add schedule
* Close CFP
* Update location page
> Add schedule to DevOpsDays DC site

- site/content/events/2015-minneapolis/proposals/Why you should care about DevOps in the public sector/index.txt
This was proposed as a 30-min talk.
> This was proposed as a 30-min talk.

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Hi, @phrawzty - in the interests of keeping the front page tidier, I'm moving Paris to "past". Please do link any videos/slides from your individual talk pages, as they become available! Thank you.
> Moving Paris to "past".

- README-Windows.md
- README.md
- Vagrantfile
- bootstrap.sh
It is very difficult to update the DevOps Days website using a Windows based operating system.  I have created an installation process which Windows users can follow.  This process creates a virtual machine using Virtual Box and then enables the user to use FTP to edit files in the VM file system.
All of the changes in this PR were created using that process.
> Feature - Windows Support

- site/content/events/2015-minneapolis/proposals/Saved or Sabotaged/index.txt
Adding proposal for msp (from Thursday - missed in previous upload)
> Adding proposal for msp (from Thursday - missed in previous upload)

- site/content/events/2015-minneapolis/_menu.txt
- site/content/events/2015-minneapolis/index.html
- site/content/events/2015-minneapolis/program/index.html
Adding program & opening keynote.
> Adding schedule & opening keynote

- site/content/events/2015-singapore/_target_date.txt
We are still looking for the right location and need to post-pone the date.
> [singapore 2015] Change date to September

- site/content/events/2015-amsterdam/program/index.html
Things should be accurate now. :)
> Wrong days and something looked horrid.

- site/content/events/2015-minneapolis/_menu.txt
- site/content/events/2015-minneapolis/index.html
- site/content/events/2015-minneapolis/program/index.html
- site/content/events/2015-minneapolis/proposals/Cheffing Etsy/index.txt
- site/content/events/2015-minneapolis/proposals/DevOps The Missing Pieces/index.txt
- site/content/events/2015-minneapolis/proposals/DevOps in the Machine/index.txt
- site/content/events/2015-minneapolis/proposals/Effortless WebPerf Monitoring/index.txt
- site/content/events/2015-minneapolis/proposals/Helping Developers Monitor Their Own Application/index.txt
- site/content/events/2015-minneapolis/proposals/Lets Safety Dance/index.txt
- site/content/events/2015-minneapolis/proposals/The New New Software Development Game/index.txt
- site/content/events/2015-minneapolis/proposals/Why you should care about DevOps in the public sector/index.txt
> Announcing the MSP 2015 program

- site/content/events/2015-minneapolis/program/index.html
It may change, but I'd like to list something.
> Adding Colleen's tentative title.

- site/content/events/2015-minneapolis/program/index.html
- site/content/events/2015-minneapolis/proposals/Rolling Your Own vs SaaS/index.txt
Adding Colleen's talk description.
> Adding Colleen's talk description.

- site/content/events/2015-amsterdam/proposals/bas-meijer__fake-it-until-you-make-it/index.txt
- site/content/events/2015-amsterdam/proposals/bert-van-der-zee-roger-wouterse__predict-the-success-of-your-upcoming-releases-with-devops-analytics/index.txt
- site/content/events/2015-amsterdam/proposals/frederieke-ubels__autonomy-at-bolcom-is-like-putting-a-man-on-the-moon/index.txt
- site/content/events/2015-amsterdam/proposals/jarl-meijer__hey-be-agile-you-know-what-i-mean/index.txt
- site/content/events/2015-amsterdam/proposals/jarl-meijer__safer/index.txt
- site/content/events/2015-amsterdam/proposals/julianna-szabo__data-quality-achieved-by-culture/index.txt
- site/content/events/2015-amsterdam/proposals/patrick-van-dissel__mayfly-dockerize-your-user-stories/index.txt
- site/content/events/2015-amsterdam/proposals/pavel-chunyayev__why-immutable-infrastructure/index.txt
- site/content/events/2015-amsterdam/proposals/steve-pereira__the-golden-pipeline/index.txt
- site/content/events/2015-amsterdam/proposals/steve-pereira__what-happens-without-traction/index.txt
After completely messing up my repo I decided to start over. I had messed it up beyond git rebase repairs. :+1: :)
> Starting from scratch and adding new talks.

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Also removing Perth from the map header since we don't have dates yet. (/cc @geekle - when there are dates, please give it a flag on the map and put it on the map header! Until then, we can keep it under "future".)
> Moving Denver and New York to "past".

- site/content/events/2015-amsterdam/proposals/alban-crequy__container-mechanics-on-linux/index.txt
- site/content/events/2015-amsterdam/proposals/alban-crequy__debugging-in-a-containerized-world/index.txt
- site/content/events/2015-amsterdam/proposals/alban-crequy__security-storage-and-retrieval/index.txt
- site/content/events/2015-amsterdam/proposals/andreas-grabner__top-quality-metrics-that-allow-you-to-deploy-faster/index.txt
- site/content/events/2015-amsterdam/proposals/dominik-bamberger__empower-your-support/index.txt
- site/content/events/2015-amsterdam/proposals/esha-seth__devops-in-action/index.txt
- site/content/events/2015-amsterdam/proposals/mandi-walls__what-can-delivery-truck-do-for-you/index.txt
- site/content/events/2015-amsterdam/proposals/tarek-negm__a-benefits-driven-approach/index.txt
- site/content/events/2015-amsterdam/proposals/tim-nolet__microservices-i-dont-always-test-but-when-i-do/index.txt
This should be the last 9 talks I think. We'll be closing our CFP tomorrow.
> [ams2015] - 9 new talks and ignites.

- site/content/events/2015-amsterdam/proposals/patrick-van-dissel__mayfly-dockerize-your-user-stories/index.txt
> Wrong name in Patrick's talk.

- site/content/events/2015-singapore/index.html
The intention is to make the text more _date agnostic_:
- June is not the target month anymore
- Once we have the date the TBA tags can be forgotten, misleading and confusing
> [singapore 2015] Remove wrong date & TBAs

- site/content/events/2015-minneapolis/program/index.html
- site/content/events/2015-minneapolis/proposals/Sports Stats 101/index.txt
Adding MSP Ignite. /cc @botchagalupe
> Adding MSP Ignite.

- site/content/events/2015-amsterdam/program/index.html
Day 1 + 2 speakers have been selected.
> [ams2015] Speakers announced

- site/content/events/2015-amsterdam/program/index.html
Small change in speaker dates.
> [ams2015] Program edit - Patrick Roelke with Mark Coleman.

- site/content/events/2015-amsterdam/program/index.html
> [ams2015] - Wrong time.

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Moving Austin to past, and Singapore to the end of 2015 since it doesn't have a month yet.
> Moving Austin to past.

- site/content/events/2015-washington-dc/index.html
- site/content/events/2015-washington-dc/location/index.html
Still recommending the Westin, but we've sold out our reserved block.
> [DC 2015] hotel rate has closed

- site/content/_upcoming.txt
- site/content/events/2015-perth/_event_date_end.txt
- site/content/events/2015-perth/_event_date_start.txt
- site/content/events/2015-perth/_target_date.txt
- site/content/events/2015-perth/location/index.html
- site/content/index.html
Added event location and date for Perth
> Added event location and date for Perth

- site/content/events/2015-melbourne/location/index.html
Fixed spelling mistake and grammar
> Fixed spelling mistake and grammar

- site/content/events/2015-minneapolis/sponsor/index.html
Reverts jedi4ever/devopsdays-webby#1736
> Revert "Gold/Silver sponsorships sold out"

- site/content/events/2015-perth/_event_date_start.txt
- site/content/events/2015-perth/_target_date.txt
- site/content/index.html
Updated event date for 2 days. 14-15 Oct.
> [Perth2015] Updated dates  for 2 day event

- site/content/events/2015-minneapolis/program/index.html
> Adding Ignite for MSP

- site/content/events/2015-amsterdam/_sponsors.txt
> [ams2015] Missing quote broke ams site.

- site/content/events/2015-amsterdam/_sponsors.txt
Last one today, I promise. :smile:
> [ams2015] Image had wrong name in _sponsors.txt

- site/content/events/2015-minneapolis/_sponsors.txt
Alter the size of the logos in the sidebar every so slightly so that they will show up three-wide.
> Alter sidebar logo size

- site/content/events/2015-chicago/_menu.txt
- site/content/events/2015-chicago/index.html
- site/content/events/2015-chicago/location/index.html
- site/content/events/2015-chicago/sponsor/index.html
> Adding the Chicago location page

- site/content/events/2015-minneapolis/program/index.html
> Ignite changes MSP

- site/content/events/2015-pittsburgh/_cfp_date_end.txt
- site/content/events/2015-pittsburgh/_cfp_date_start.txt
Don't merge until two of these people post agreement:
@cmluciano
@meatballhat
@sethvargo
@carsomyr
@littleidea
> Sets Pittsburgh 2015 CFP dates

- site/content/events/2015-pittsburgh/conduct/index.html
This is another one that others should see, even though the changes are small.
@cmluciano
@littleidea
@carsomyr
@meatballhat
@sethvargo
> Conduct modifications for Pittsburgh 2015

- site/content/events/2015-pittsburgh/_team_local.txt
Unless there are nays from 
@cmluciano
@littleidea
@carsomyr
@meatballhat
@sethvargo
> Adds Pittsburgh 2015 organizers' twitters to contact info

- site/content/events/2015-pittsburgh/propose/index.html
:hand: :no_entry_sign: :red_circle: 
This is blocked on cmluciano/blinder-dod#3.
@cmluciano or I will post here when this can be merged. Otherwise, folks will get a big ol' white page.
> Fills out Pittsburgh 2015 proposals page

- site/content/events/2015-pittsburgh/registration/index.html
Finally ready to go after Showclix added a missed permission.
> Embeds registration for Pittsburgh 2015

- site/content/events/2015-pittsburgh/location/index.html
It's too close to the sponsor images.
> Reduce Pittsburgh 2015 map to give some buffer space

- site/content/events/2015-pittsburgh/_menu.txt
- site/content/events/2015-pittsburgh/index.html
- site/content/events/2015-pittsburgh/travel/index.html
Would love a lookover by @sethvargo @littleidea @meatballhat @carsomyr @cmluciano.
> Adds hotel and travel information for Pittsburgh 2015

- site/content/events/2015-pittsburgh/location/index.html
I really need to find the time to make webby work on my machine.
> Fixes larger map link on Pittsburgh 2015

- site/content/events/2015-washington-dc/conduct/index.html
- site/content/events/2015-washington-dc/index.html
* Livestream and Etherpad links
* Reiterate the CoC
* Provide email address to reach on-call orgs
> [DC 2015] T-1d updates

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/events/2015-washington-dc/conduct/index.html
- site/content/events/2015-washington-dc/index.html
- site/content/index.html
* Update front page text
* Remove VictorOps/direct contact info from CoC page, replace with
organizers mail
> [DC 2015] that's all, folks!

- site/content/events/2015-berlin/_cfp_date_announce.txt
- site/content/events/2015-berlin/_cfp_date_end.txt
- site/content/events/2015-berlin/_cfp_date_start.txt
- site/content/events/2015-berlin/propose/index.html
Call for proposals from June 15th to Aug 15th
> Add call for proposals

- site/content/events/2015-pittsburgh/index.html
> Corrects CFP date on Pittsburgh 2015 index

- site/content/events/2015-berlin/propose/index.html
This fixes the mess my <p> made of the propose part of the berlin 2015 site.
> Last edit broke rendering.

- README.md
- site/content/events/2015-melbourne/program/index.html
- site/content/events/2015-melbourne/proposals/I1/index.txt
- site/content/events/2015-melbourne/proposals/I2/index.txt
- site/content/events/2015-melbourne/proposals/I3/index.txt
- site/content/events/2015-melbourne/proposals/I4/index.txt
- site/content/events/2015-melbourne/proposals/T1/index.txt
- site/content/events/2015-melbourne/proposals/T2/index.txt
- site/content/events/2015-melbourne/proposals/T3/index.txt
- site/content/events/2015-melbourne/proposals/T4/index.txt
- site/content/events/2015-melbourne/proposals/T5/index.txt
- site/content/events/2015-melbourne/proposals/T6/index.txt
- site/content/events/2015-melbourne/proposals/T7/index.txt
- site/content/events/2015-melbourne/proposals/T8/index.txt
Populated Agenda for Melbourne 2015.
Added accepted Talks & Ignites.
Some minor update on the install/setup instructions
> Melbourne 2015 agenda

- site/content/events/2015-melbourne/program/index.html
- site/content/events/2015-melbourne/proposals/T1/index.txt
Swap Jonah and Lindsay to fit will App Dynamics scheduling.
> Agenda swap speakers

- site/content/events/2015-pittsburgh/index.html
Needs a :+1: from one of @sethvargo @meatballhat @carsomyr @j41manning @littleidea or @cmluciano _and_ a :+1: from @cwest
@cwest: let me know if you'd like me to use a different URL for you other than your Twitter.
> Initializes Pittsburgh 2015 testimonials section with input from Casey West!

- site/content/events/2015-pittsburgh/propose/index.html
Need some agreement from @sethvargo @cmluciano @carsomyr @meatballhat @littleidea @j41manning, but this is the same language  we discussed on Friday.
> Notes interest in security talks for Pittsburgh 2015

- site/content/events/2015-pittsburgh/program/index.html
- site/content/events/2015-pittsburgh/proposals/how-to-debug-anything/index.txt
> Add Sam Kottler's talk

- site/content/events/2015-minneapolis/program/index.html
Rearranging Ignite schedule a bit.
> Ignite speaker needed to cancel.

- site/content/events/2015-boston/_menu.txt
- site/content/events/2015-boston/index.html
- site/content/events/2015-boston/registration/index.html
We're ready to accept registrations! :D
> Add registration links to Boston 2015

- site/content/events/2015-pittsburgh/index.html
Need a :+1: from one of @sethvargo @cmluciano @littleidea @meatballhat @j41manning @carsomyr
And a :+1: from @cwinters
> Adds Chris Winters' testimonial to Pittsburgh 2015 index

- site/content/events/2015-pittsburgh/program/index.html
Needs approval from a few of @carsomyr @j41manning @sethvargo @meatballhat @cmluciano @littleidea
> Pittsburgh 2015: Breaks talks block into talks and breaks

- site/content/events/2015-pittsburgh/index.html
Approvals
----
* Both: @cwest @cwinters 
* One of: @sethvargo @j41manning @cmluciano @littleidea @meatballhat @carsomyr
> Adds pictures to testimonials for Pittsburgh 2015

- site/content/_past.txt
- site/content/_upcoming.txt
The Amsterdam Edition has concluded for this year! Time to move it to `_past.txt`
> moves Amsterdam to "past"

- Gemfile.lock
- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Re-ordering in chronological order.
Removing AMS from map
> Front page cleanup

- site/content/events/2015-pittsburgh/_cfp_date_end.txt
In accordance with https://twitter.com/devopsdayspgh/status/614931342309130240
> Extends Pittsburgh 2015 CFP date

- site/content/events/2015-perth/_cfp_date_announce.txt
- site/content/events/2015-perth/_cfp_date_end.txt
- site/content/events/2015-perth/_cfp_date_start.txt
- site/content/events/2015-perth/_sponsors.txt
- site/content/events/2015-perth/_team_local.txt
- site/content/events/2015-perth/program/index.html
- site/content/events/2015-perth/registration/index.html
- site/content/events/2015-perth/sponsor/index.html
Updated the Perth event with dates and organiser names.  No need to add them to the email lists.
> Updated Perth 2015 information

- site/content/events/2015-minneapolis/_team_local.txt
Because he's doing as much work as any of us!
> Joe Laha joining as official organizer for MSP.

- site/content/events/2015-minneapolis/program/index.html
Presentation retitle for Ignite at MSP.
> Presentation retitle for Ignite at MSP.

- site/content/events/2015-pittsburgh/sponsor/index.html
@sethvargo This wording is an approximation/embellishment of the language we discussed.
@carsomyr @meatballhat @cmluciano @j41manning @littleidea
> Adds Pittsburgh 2015 sponsorship day-of details

- site/content/events/2015-pittsburgh/location/index.html
@sethvargo @cmluciano Is this what yinz had in mind?
@j41manning @carsomyr @meatballhat @littleidea Input?
> Adds WiFi note to Pittsburgh 2015 location page

- site/content/_future.txt
> [SIN-15] Remove duplicated link to future event

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Also moving Detroit's label so it doesn't cover Boston's.
> Moving MSP to past

- site/content/events/2015-singapore/sponsor/index.html
This commit enables the 'special packages' on the sponsor page.
> [SIN-15] sponsor: Add special packages

- site/content/events/2015-pittsburgh/proposals/application-orchestration-with-kubernetes/index.txt
- site/content/events/2015-pittsburgh/proposals/busting-silos-and-red-tape-devops-in-federal-government/index.txt
- site/content/events/2015-pittsburgh/proposals/conversation-201-what-stuttering-can-teach-you-about-connecting-with-people/index.txt
- site/content/events/2015-pittsburgh/proposals/ethical-and-sustainable-on-call/index.txt
- site/content/events/2015-pittsburgh/proposals/how-to-debug-anything/index.txt
- site/content/events/2015-pittsburgh/proposals/security-for-humans/index.txt
- site/content/events/2015-pittsburgh/proposals/the-incredible-shrinking-operating-system/index.txt
- site/content/events/2015-pittsburgh/proposals/vt-tbd/index.txt
Some review by @sethvargo @cmluciano @carsomyr @littleidea @j41manning @meatballhat would be welcome, but this should go up ASAP.
> Adds Pittsburgh 2015 speakers!

- site/content/events/2015-pittsburgh/index.html
Need some approvals from @sethvargo @cmluciano @littleidea @j41manning @carsomyr @meatballhat
Also a :+1: from @cwest @grubernaut and @melancholyfleur would be welcome, too!
> Adds video testimonials to Pittsburgh 2015

- site/content/events/2015-pittsburgh/_team_local.txt
Go go @j41manning :beers:
Should have done this a couple of weeks ago.
> Adds Jenny to Pittsburgh 2015 staff

- site/content/events/2015-minneapolis/proposals/DevOps The Missing Pieces/index.txt
- site/content/events/2015-minneapolis/proposals/Rolling Your Own vs SaaS/index.txt
- site/content/events/2015-minneapolis/proposals/Why you should care about DevOps in the public sector/index.txt
Slides and video for three of MSP's talks.
> Slides and video for three of MSP's talks.

- site/content/events/2015-ohio/_event_date_end.txt
- site/content/events/2015-ohio/_event_date_start.txt
- site/content/events/2015-ohio/index.html
Just adding the dates, updated formatting a bit, and replaced `<center>` with `<div style="text-align: center">`.
> 2015 Ohio, Adding dates 18-19 November

- site/content/_upcoming.txt
- site/content/index.html
Ohio and Singapore should both be on the map at this point.
> Ohio and Singapore: adding to the map.

- site/content/index.html
The current date on the map is showing September. Needs to be October.
This commit fixed that.
> [SIN 15] Fix date for event from Sep > Oct

- site/content/_future.txt
- site/content/_upcoming.txt
Also sort future events by date.
> [SIN-15] Add Singapore to `upcoming` list

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
And arranging the Perth banner so it's easier to read.
> Moving Melbourne to past.

- site/content/events/2015-siliconvalley/_sponsors.txt
Fix file extension on the SFX logo.
> update signalfx logo

- site/content/events/2015-singapore/presentations/devops-meetup.html
- site/content/events/2015-singapore/presentations/devopsdays-pitch.html
- site/content/events/2015-singapore/presentations/index.html
The slides show some more facts about Singapore that visitors might not yet
know.
We can use these slides as a nice introduction to Singapore (for example on meetups).
Feel free to add more facts and images.
> [SIN-15] Add presentations for promoting the event

- site/content/events/2015-singapore/_menu.txt
- site/content/events/2015-singapore/index.html
- site/content/events/2015-singapore/registration/index.html
We enable registration tab and add a note for the visitors to come back.
> [SIN-15] Add a note when 'registrations' opens

- site/content/events/2015-boston/_sponsors.txt
Updating the logz.io sponsor link
> Boston update to logz.io sponsor link

- site/content/events/2015-singapore/index.html
- site/content/events/2015-singapore/registration/index.html
Also add details on the DevOps Meetup to provide more context.
> [SIN-15] Update registration date

- site/content/events/2015-pittsburgh/program/index.html
@sethvargo @meatballhat @j41manning @cmluciano @carsomyr
@bridgetkromhout @jedi4ever merge ASAP please :beers: :beers: :beers:
> Extends Pittsburgh 2015 Lunch to what it really should be

- site/content/events/2015-berlin/proposals/Automating_Data_Deployments_with_Distributed_Databases/index.txt
- site/content/events/2015-berlin/proposals/How_to_run_one_of_the_top_100_US_from_Germany/index.txt
- site/content/events/2015-berlin/proposals/infrastructure_in_code_dockerfiles_and_dockercompose/index.txt
- site/content/events/2015-berlin/proposals/why_mobile_and_frontend_developers/index.txt
Next rounds of proposals, we're nearing EOCFP.
> Next round of proposals, Fix Ben's name

- site/content/events/2015-singapore/index.html
- site/content/events/2015-singapore/registration/index.html
Replace the content with ti.to's javascript widget:
https://ti.to/docs/widget
> [SIN-15] Enable registration form

- site/content/events/2015-perth/_team_local.txt
- site/content/events/2015-perth/index.html
Changed the Layout of the Perth DevOpsDays Index page.
Added name of the organizing committee member.
> Changes the Perth Event Page/added new member

- site/content/events/2015-berlin/proposals/Agile_and_DevOps_for_Services/index.txt
- site/content/events/2015-berlin/proposals/Ansible_A_Love_Hate_Relationship/index.txt
- site/content/events/2015-berlin/proposals/Because_Your_Infrastructure_Deserves_tests_too/index.txt
- site/content/events/2015-berlin/proposals/Containers_DevOps_Mesos/index.txt
- site/content/events/2015-berlin/proposals/Culture_First/index.txt
- site/content/events/2015-berlin/proposals/Defining_DevOps/index.txt
- site/content/events/2015-berlin/proposals/DevOps_and_Security/index.txt
- site/content/events/2015-berlin/proposals/DevOps_at_NI/index.txt
- site/content/events/2015-berlin/proposals/From_Hero_to_Zero/index.txt
- site/content/events/2015-berlin/proposals/How_to_Store_and_retrieve_container_images_securely/index.txt
- site/content/events/2015-berlin/proposals/Infrastructure_as_code_Ansible_How_to_Make_your_Life_Easier/index.txt
- site/content/events/2015-berlin/proposals/Lessons_from_the_trenches/index.txt
- site/content/events/2015-berlin/proposals/Lets_have_a_devops_team/index.txt
- site/content/events/2015-berlin/proposals/Monitoring_Java_Applications_with_Jolokia/index.txt
- site/content/events/2015-berlin/proposals/Net_Innovation_Why_devops_needs_to_extend/index.txt
- site/content/events/2015-berlin/proposals/Power_in_the_workplace_and_woment_in_tech/index.txt
- site/content/events/2015-berlin/proposals/The_TICK_stack/index.txt
- site/content/events/2015-berlin/proposals/Zero_Downtime_Deployment_with_Ansible/index.txt
These are the last proposals for the 2015 edition of DevOpsDays Berlin.
> Last round of proposals

- site/content/events/2015-berlin/proposals/Power_in_the_workplace_and_woment_in_tech/index.txt
Last proposals they were. Last fixes they were not :)
> Inga is actually called Höltmann

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
Moving Pittsburgh to the past.
> Moving Pittsburgh to the past.

- site/content/events/2015-boston/_menu.txt
- site/content/events/2015-boston/index.html
- site/content/events/2015-boston/program/index.html
We have 8 of our 9 speaker slots ready, so we'd like to get that up on the site ASAP!
We're also totally sold out so we're telling people about the waitlist.
> Boston 2015 speakers

- site/content/events/2015-berlin/proposals/CD_with_Nix/index.txt
- site/content/events/2015-berlin/proposals/Immutable_Infrastructure_with_Nix/index.txt
- site/content/events/2015-berlin/proposals/In_The_old_days/index.txt
These are the last accepted proposals.
> very last round of talks

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/events/2015-chicago/_menu.txt
- site/content/events/2015-chicago/index.html
- site/content/events/2015-chicago/program/index.html
- site/content/index.html
move 2015 chicago to the past and clean up some of the html for the future events (fewer errors reported by html validator now)
> [2015-chicago] move 2015-chicago event to the past

- site/content/events/2015-berlin/proposals/DevOps_Culture_at_Mapbox/index.txt
Looks like I missed that one in my inbox.
> Missed Proposal

- site/content/events/2015-siliconvalley/_menu.txt
- site/content/events/2015-siliconvalley/registration/index.html
Open registration for DevOpsDays 2015
> add registration for SV 2015

- site/content/events/2015-siliconvalley/_menu.txt
- site/content/events/2015-siliconvalley/_sponsors.txt
- Fix issue with rackspace logo
- Update registration link in menu bar.
> Fix issue with rackspace logo

- site/content/events/2015-berlin/proposals/nix_the_purely_functional_Package_manager/index.txt
We had one presenter going "ignite" with a slightly different content ...
> new ignite (presentation -> ignite), selected

- Vagrantfile
- site/content/events/2015-berlin/proposals/nix_the_purely_functional_Package_manager/index.txt
- site/content/events/2015-siliconvalley/proposals/Errbot, a chatbot the python way/index.txt
- site/content/events/2015-siliconvalley/proposals/Infrastructure Automation and how Dev Ops Can Utilize the New Without Forgetting the Old/index.txt
- site/content/events/2015-siliconvalley/proposals/The Importance of Visualization in Anomaly Detection - An ElasticSearch Example/index.txt
- site/content/events/2015-washington-dc/_menu.txt
- site/content/events/2015-washington-dc/index.html
- site/content/events/2015-washington-dc/program/corman.html
- site/content/events/2015-washington-dc/program/esher.html
- site/content/events/2015-washington-dc/program/fayer.html
- site/content/events/2015-washington-dc/program/index.html
- site/content/events/2015-washington-dc/program/meenan.html
- site/content/events/2015-washington-dc/program/uspto.html
- site/content/events/2015-washington-dc/program/welcome.html
- site/content/events/2015-washington-dc/program/willis.html
Adding some of the DC 2015 speaker pages which include audio, video, and slides from the talks.  More to come but this is OK to merge now.
> DC speaker pages

- site/content/events/2015-washington-dc/program/brown.html
- site/content/events/2015-washington-dc/program/burroughs.html
- site/content/events/2015-washington-dc/program/corman.html
- site/content/events/2015-washington-dc/program/daczewitz.html
- site/content/events/2015-washington-dc/program/demming.html
- site/content/events/2015-washington-dc/program/donbeck.html
- site/content/events/2015-washington-dc/program/dzirasa.html
- site/content/events/2015-washington-dc/program/esher.html
- site/content/events/2015-washington-dc/program/fayer.html
- site/content/events/2015-washington-dc/program/foodfight.html
- site/content/events/2015-washington-dc/program/index.html
- site/content/events/2015-washington-dc/program/kraft.html
- site/content/events/2015-washington-dc/program/malone.html
- site/content/events/2015-washington-dc/program/meenan.html
- site/content/events/2015-washington-dc/program/nescot.html
- site/content/events/2015-washington-dc/program/nichols.html
- site/content/events/2015-washington-dc/program/oops.html
- site/content/events/2015-washington-dc/program/openscap.html
- site/content/events/2015-washington-dc/program/openspaces.html
- site/content/events/2015-washington-dc/program/schwartz.html
- site/content/events/2015-washington-dc/program/simpson.html
- site/content/events/2015-washington-dc/program/uspto.html
- site/content/events/2015-washington-dc/program/welcome-day2.html
- site/content/events/2015-washington-dc/program/welcome.html
- site/content/events/2015-washington-dc/program/willis.html
the remaining talks from DC 2015
> DC speaker pages - the rest

- site/content/events/2015-perth/index.html
Unfortunately the Perth event has been cancelled.
Will be updated the other parts of the website soon. This is just the initial call out on the main page
> Perth even has been cancelled

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/index.html
Can @geekle merge this?
/cc @BhupenderKhatkar @glennsarti @citrady
> Removing Perth from front page due to cancellation.

- site/content/_upcoming.txt
Just a cosmetic change to provide a divider between the events.
> upcoming: Add divider for TLV and SIN event

- site/content/events/2015-berlin/proposals/Biased_thought_patterns_considered_harmful/index.txt
Talk stays the same, title changes.
> changed the title of the talk

- site/content/events/2015-singapore/index.html
This helps ppl that travel to Singapore the first time.
> [SIN-15] index: Add link to `location`

- site/content/events/2015-singapore/location/index.html
Fixes issues with PR 2072 (see comments)
> [SIN-15] location: Add `eventhome` variable

- site/content/events/2015-singapore/_sponsors.txt
- site/content/events/2015-singapore/conduct/index.html
- site/content/events/2015-singapore/contact/index.html
- site/content/events/2015-singapore/index.html
- site/content/events/2015-singapore/location/index.html
- site/content/events/2015-singapore/program/index.html
- site/content/events/2015-singapore/proposals/index.txt
- site/content/events/2015-singapore/propose/index.html
- site/content/events/2015-singapore/registration/index.html
- site/content/events/2015-singapore/sponsor/index.html
- site/layouts/event_singapore.txt
This allows our Host sponsors to be in the lead position (because they pay the lead package).
See http://www.devopsdays.org/events/2015-singapore/sponsor/#sponsorship for more context on the packages.
We also update sponsor related notes that are reflected in our contract.
> [SIN-15] layouts: create dedicated layout for SIN

- site/content/events/2015-singapore/_menu.txt
- site/content/events/2015-singapore/program/index.html
- site/content/events/2015-singapore/proposals/Life at REA Group/index.txt
- site/content/events/2015-singapore/proposals/State Of The DevOps Union/index.txt
- site/content/events/2015-singapore/proposals/index.txt
The reason why we introduce the new page property 'talk_title' is that
we want to avoid multiline titles which distroy the page layout (affect
the sponsor layout etc)
> [SIN-15] program/proposals: Add keynotes

- site/content/events/2015-singapore/_sponsors.txt
Grouped into GOLD by accident.
> [SIN-15] sponsors: Add `redhat` to silver sponsors

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/index.html
> Moving Boston to past

- site/content/events/2015-singapore/presentations/devops-meetup.html
- site/content/events/2015-singapore/presentations/devopsdays-pitch.html
- site/content/events/2015-singapore/presentations/index.html
- site/content/events/2015-singapore/presentations/program.html
We want to show our new sponsors on the presentation slides as well.
> [SIN-15] presentations: Add sponsors to the slides

- site/content/events/2015-berlin/_menu.txt
- site/content/events/2015-berlin/program/index.html
- site/content/events/2015-berlin/proposals/Ansible_A_Love_Hate_Relationship/index.txt
- site/content/events/2015-berlin/proposals/DevOps_Tooling_Landscape/index.txt
- site/content/events/2015-berlin/proposals/Hiring_Infrastructure_Operating_Engineers/index.txt
- site/content/events/2015-berlin/proposals/Making_more_people_welcome_and_safe/index.txt
- site/content/events/2015-berlin/propose/index.html
This PR add the Berlin 2015 program.
> Berlin 2015: Publish program

- site/content/events/2016-saltlakecity/index.html
- site/content/events/2016-saltlakecity/proposals/index.txt
Corrections to slight display issues (/cc @davidasnider).
> Minor corrections - SLC

- site/content/events/2016-template/proposals/index.txt
Not sure how this happened, but fixed now.
> Added missing layout type for template.

- site/content/events/2016-philadelphia/_target_location.txt
- site/content/events/2016-philadelphia/sponsor/index.html
- site/content/events/2016-saltlakecity/sponsor/index.html
- site/content/events/2016-template/sponsor/index.html
Like it says on the tin. /cc @pietrojs
> small corrections to philly & template issue

- site/content/events/2016-philadelphia/_team_local.txt
To prevent this:
(Your other option would be newlines - going with the standard for now. Feel free to adjust, @pietrojs.)
> Format fix.

- site/content/events/2015-singapore/program/index.html
- site/content/events/2015-singapore/proposals/How a payment processing company turned into a software release factory/index.txt
- site/content/events/2015-singapore/proposals/The Paradox of Progress/index.txt
- site/content/events/2015-singapore/proposals/index.txt
We also update the program accordingly.
> [SIN-15] proposals: Add new talks

- site/content/events/2015-singapore/program/index.html
Speaker is not available on Friday.
> [SIN-15] program: Update time schedule for talks

- site/content/events/2015-warsaw/location/index.html
> 2015 - Warsaw - changes in the venue page

- site/content/events/2015-berlin/program/index.html
- site/content/events/2015-berlin/proposals/Ansible_A_Love_Hate_Relationship/index.txt
- site/content/events/2015-berlin/proposals/From_Hero_to_Zero/index.txt
> changes to speakers

- site/content/events/2016-philadelphia/_team_local.txt
> 2016-philly: Add DaveK to the team list

- site/content/events/2015-singapore/proposals/index.txt
We also clean up code to make the page more maintainable.
> [SIN-15] proposals: Add `coming soon`

- site/content/events/2015-telaviv/program/main_j_paul_reed.html
Just some minor things.
Heads up to @m1keil and @shar1z :-)
> Fix minor typos in my talk description.

- site/content/events/2016-london/_email_organizers.txt
- site/content/events/2016-london/_email_proposals.txt
> London will be in 2016.

- site/content/events/2016-edinburgh/index.html
- site/content/events/2016-london/index.html
- site/content/events/2016-seattle/index.html
Commenting out the broken images left in place due to my original poor default choice.
> Broken images weren't a great default.

- site/content/events/2015-berlin/program/index.html
This should be the final program (at least it now has all slots filled)
> Final(?) schedule for Berlin

- site/content/events/2016-saltlakecity/_sponsors.txt
- site/content/events/2016-saltlakecity/conduct/index.html
- site/content/events/2016-saltlakecity/contact/index.html
- site/content/events/2016-saltlakecity/index.html
- site/content/events/2016-saltlakecity/location/index.html
- site/content/events/2016-saltlakecity/program/index.html
- site/content/events/2016-saltlakecity/proposals/index.txt
- site/content/events/2016-saltlakecity/propose/index.html
- site/content/events/2016-saltlakecity/registration/index.html
- site/content/events/2016-saltlakecity/sponsor/index.html
- site/layouts/event_slc.txt
Changed sponsor levels to "Black Diamond", "Blue Square", and "Green Circle", in line with the various ski slope difficulty levels.   Modified the registration page to include the side bar.
> [SLC] Rename sponsor levels, minor mods to formatting

- site/content/events/2015-ohio/_sponsors.txt
- site/content/events/2015-ohio/program/index.html
- site/content/events/2015-ohio/proposals/i1-1/index.txt
- site/content/events/2015-ohio/proposals/i1-2/index.txt
- site/content/events/2015-ohio/proposals/i1-3/index.txt
- site/content/events/2015-ohio/proposals/i1-4/index.txt
- site/content/events/2015-ohio/proposals/i2-1/index.txt
- site/content/events/2015-ohio/proposals/i2-2/index.txt
- site/content/events/2015-ohio/proposals/i2-3/index.txt
- site/content/events/2015-ohio/proposals/i2-4/index.txt
- site/content/events/2015-ohio/proposals/k1-1/index.txt
- site/content/events/2015-ohio/proposals/k1-2/index.txt
- site/content/events/2015-ohio/proposals/k1-3/index.txt
- site/content/events/2015-ohio/proposals/k1-4/index.txt
- site/content/events/2015-ohio/proposals/k2-1/index.txt
- site/content/events/2015-ohio/proposals/k2-2/index.txt
- site/content/events/2015-ohio/proposals/k2-3/index.txt
- site/content/events/2015-ohio/proposals/k2-4/index.txt
Moved some of the logos.
Added in all of the select proposal abstracts, and added links to the schedule.
> Ohio 2015: Abstracts, logo update.

- site/content/events/2015-singapore/location/index.html
Kudos to [devfestasia](https://twitter.com/devfestasia)!
> [SIN-15] location: Add link to recommendations

- site/content/events/2015-siliconvalley/_menu.txt
- site/content/events/2015-siliconvalley/scholarship/index.html
To Launch DevOpsDays Diversity Scholarship, added the page which includes the Scholarship Application (embedded in a Google Form). Also added the scholarship to event's menu. Verified the html and navigation by building through webby per README.md. 
To give some verification, I'm on the list of organizers for DevOpsDays Silicon Valley(feel free to contact chair iennae aka Jennifer Davis).
> Adding Diversity Scholarship Page to DevOpsDays SiliconValley

- site/content/events/2015-siliconvalley/scholarship/index.html
Talked with Jennifer and changing the wording.
> Updating wording on scholarship mission after review from chair.

- site/content/events/2015-ohio/proposals/i2-2/index.txt
Simply adding a missing ignite abstract (Day 2, ignite 2).
> Ohio 2015: Adding missing ignite abstract.

- site/content/events/2015-ohio/proposals/k1-1/index.txt
Finally got the abstract for the day 1 keynote! Just adding it in.
> Ohio 2015: Adding Day 1 Keynote Abstract

- site/content/events/2015-siliconvalley/_menu.txt
- site/content/events/2015-siliconvalley/program/index.html
Fixing missing </div> and adding program, removing a few misplaced ids.
> minor html updates to program and fixing menu to include program

- site/content/events/2015-siliconvalley/scholarship/index.html
Modified form width to be more friendly to the page layout.
> Diversitysv

- site/content/events/2015-singapore/index.html
I like it better that way.
Or only remove the submit proposals?
> less text to make it easier to navigate

- site/layouts/event_singapore.txt
This allows visitors to leave comments to a talk.
This way we can gather feedback on how to improve our program.
> [SIN-15] layout: Add `disqus_comments` partial

- site/content/events/2015-singapore/_sponsors.txt
The previous version did lead to linebreaks which cluttered the layout.
> [SIN-15] sponsors: Align silver logos

- site/layouts/event_singapore.txt
This allows us to point directly to the form
> [SIN-15] layouts: Add anchor for feedback form

- site/content/events/2015-berlin/program/index.html
- site/content/events/2015-berlin/proposals/Immutable_Infrastructure_with_Nix/index.txt
Rok merged the contents of his talk into a small ignite - thus the changed title and content.
> Change title of ignite

- site/content/events/2015-berlin/program/index.html
The speaker cancelled his talk
> Removed cancelled Ignite

- site/content/events/2015-berlin/program/index.html
Update the program to include link to slides. More to follow in the next days....
> [Berlin 2015] Linking slides part 1.

- site/content/events/2016-saltlakecity/_team_local.txt
We have a new team member! Yay!
> [SLC] Add new organizer - Allia DeAngelis

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
Moving Berlin & Charlotte to past; slight chronological re-order of future.
> Moving Berlin & Charlotte to past

- site/content/contact/_team_global.txt
Updated to show that Jennifer has joined the core team.
> Added Jennifer.

- site/content/events/2015-ohio/index.html
- site/content/events/2015-ohio/location/index.html
Simple corrections to a misspelling.
> Ohio 2015: Misspelled Information.

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
Moving Silicon Valley to past.
> Moving Silicon Valley to past.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
* Kiel
* Washington, DC
* Minneapolis
All three added to the top nav and to the map
> Add upcoming events with confirmed dates to the home page:

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
- detroit to past
- seattle's dates
- chronological order
> Adjusted front page upcoming events

- site/content/events/2016-saltlakecity/_team_local.txt
We added a new organizer, Mike Duffy!
> [SLC2016] Add Mike Duffy to local organizers

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
> Moved Ohio to past.

- site/content/events/2016-seattle/_sponsors.txt
- site/content/events/2016-seattle/sponsor/index.html
added sponsorship details and links
> Added sponsorship details

- site/content/events/2016-london/_cfp_date_end.txt
- site/content/events/2016-london/_cfp_date_start.txt
- site/content/events/2016-london/_event_date_end.txt
- site/content/events/2016-london/_event_date_start.txt
- site/content/events/2016-london/_sponsors.txt
- site/content/events/2016-london/_team_local.txt
- site/content/events/2016-london/contact/index.html
- site/content/events/2016-london/index.html
- site/content/events/2016-london/location/index.html
- site/content/events/2016-london/program/index.html
- site/content/events/2016-london/proposals/index.txt
- site/content/events/2016-london/propose/index.html
- site/content/events/2016-london/registration/index.html
- site/content/events/2016-london/sponsor/index.html
Please can you accept this to publish my London 2016 event updates?  I tested these manually.  I was rather hoping "webby test" would do something - no such luck.  Any tips on automated testing?  If so, happy to do these first.
> London 2016 updates

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
Added London dates & marker to the front page.
> Updated front page for London 2016.

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
> Moving Warsaw to past.

- site/content/events/2016-london/sponsor/index.html
Needed to add that quoted sponsor prices don't include tax.
> Adding VAT statement

- site/content/events/2016-kiel/sponsor/index.html
Hi,
Please merge changes.
Thank you,
Maik
> wrong numbers in sponsor tickets row fixed

- site/content/events/2016-istanbul/_team_local.txt
Adding new organizer to Istanbul.
> Adding new organizer to Istanbul.

- site/content/events/2016-philadelphia/_team_local.txt
Removing Hector per @peterjshan.
> Removing Hector per Pete Shannon

- site/content/_future.txt
> Removed Edinburgh.

- site/content/_future.txt
- site/content/js/googlemaps_content.js
Per Ernest Mueller - CC @scottsbaldwin.
> Austin changes on front page.

- site/content/events/2016-austin/_target_location.txt
- site/content/events/2016-austin/index.html
- site/content/events/2016-austin/location/index.html
Location update.
Per Ernest Mueller, CC @scottsbaldwin.
> Austin location change

- site/content/events/2016-kiel/registration/index.html
> ticket registration is now open

- site/content/events/2016-losangeles-1day/_sponsors.txt
- site/content/events/2016-losangeles-1day/conduct/index.html
- site/content/events/2016-losangeles-1day/contact/index.html
- site/content/events/2016-losangeles-1day/index.html
- site/content/events/2016-losangeles-1day/location/index.html
- site/content/events/2016-losangeles-1day/program/index.html
- site/content/events/2016-losangeles-1day/propose/index.html
- site/content/events/2016-losangeles-1day/registration/index.html
- site/content/events/2016-losangeles-1day/sponsor/index.html
- site/layouts/event_la1day.txt
Fixing sponsors layout for la-1day.
> Fixing sponsors layout for la-1day.

- site/content/events/2016-washington-dc/location/index.html
- Rearrange text
- Update airport link
- Replace Google Map
> [DC 2016] Location page updates

- site/content/events/2016-washington-dc/conduct/index.html
In final graf, replace "Although the conference is over..." language
with information on on-call orgs for 2016.
> [DC 2016] CoC page update

- site/content/events/2016-losangeles-1day/_sponsors.txt
add sumologic to DevOpsDay LA sponsor list
> add sumologic to DevOpsDay LA sponsor list

- site/content/_future.txt
Clarifying that Raleigh will be in the fall.
> Clarifying that Raleigh will be in the fall.

- site/content/events/2016-raleigh/_team_local.txt
Adding Mark Hinkle as requested.
> Adding Mark Hinkle as requested.

- site/content/events/2016-vancouver/_team_local.txt
> DevOpsDays Vancouver 2016 - Add Chris!

- site/content/events/2016-kiel/proposals/Building_a_Workflow_for_Efficient_Development_via_Git/index.txt
- site/content/events/2016-kiel/proposals/Pipeline-as-Code_with_Jenkins/index.txt
- site/content/events/2016-kiel/proposals/Scaling_Culture/index.txt
- site/content/events/2016-kiel/proposals/Working_in_and_with_Open_Source_Communities/index.txt
Hi,
please merge the latest changes.
thank you,
Maik
> added proposal:Working in and with Open Source Communities

- site/content/events/2016-toronto/_cfp_date_announce.txt
Sigh. Lesson learned about trying to do a quick fix.
> Toronto 2016 - Really fix the program announce date.

- site/content/events/2016-atlanta/_team_local.txt
Adding new Atlanta team member
> Adding new Atlanta team member

- site/content/events/2016-portland/_team_local.txt
Updating Portland team.
CC @BillWeiss.
> Updating Portland team.

- site/content/events/2016-kiel/proposals/Deployment_Scripts_Are_Dead/index.txt
- site/content/events/2016-kiel/proposals/Lessons_Learned_from_Industrial_Failures/index.txt
- Software Development Lessons Learned from Industrial Failures in the 1980s
- Deployment Scripts Are Dead, Meet Rultor
please merge the changes to the main site.
Thank you,
Maik
> added proposals

- site/content/events/2016-portland/_team_local.txt
Sorry Rich, missed you somehow :(
> Add one more organizer

- site/content/events/2016-austin/_team_local.txt
Adding new organizer per Ernest Mueller.
> Adding new organizer per Ernest Mueller.

- site/content/events/2016-minneapolis/_menu.txt
- site/content/events/2016-minneapolis/proposals/I Find Your Lack of Silos Disturbing: DevOps in the Enterprise/index.txt
- site/content/events/2016-minneapolis/proposals/Wrangling Data with Git/index.txt
- site/content/events/2016-minneapolis/proposals/index.txt
- site/content/events/2016-minneapolis/propose/index.html
> Adding talks to MSP.

- site/content/events/2016-portland/sponsor/index.html
He tried reading the error logs, you won't believe what happened next!
> One weird trick to actually render your templates!

- site/content/events/2016-portland/sponsor/index.html
- Small layout tweaks
- Remove references to vendor booths
- Maybe we'll have more than one platinum sponsor?
> Trivial 2016 PDX changes

- site/content/events/2016-kiel/proposals/Continuous_Integration_for_DevOps/index.txt
- site/content/events/2016-kiel/proposals/Load_balancing_at_SoundCloud/index.txt
- Load balancing at SoundCloud
- Continuous Integration for DevOps
thank you,
Maik
> added proposals:

- site/content/events/2016-london/location/index.html
- site/content/events/2016-london/proposals/The Surprising Truth about DevOps in Banking/index.txt
- site/content/events/2016-london/registration/index.html
...and fixed a proposal that wasn't displaying.
> Registration form

- site/content/events/2016-vancouver/sponsor/index.html
* Happy Hour sponsors also get some tickets to main event
> DevOpsDays Vancouver 2016 - update sponsorship details

- site/content/js/googlemaps_content.js
Atlanta isn't in Texas, despite what copypasta might say. Also, Amsterdam and London both can be visible.
> Map corrections.

- site/content/events/2016-kiel/proposals/Keep_it_simple/index.txt
- site/content/events/2016-kiel/proposals/Single_Page_Applications/index.txt
- added proposal: Making Single Page Applications (SPA) faster
Thank you,
Maik
> - fixed talk flag for ignite

- site/content/events/2016-seattle/sponsor/index.html
Fixed a spelling error on the sponsor page
> fixed spelling error

- site/content/events/2016-kiel/proposals/Application_Performance_Management/index.txt
- site/content/events/2016-kiel/proposals/Building_Micro-Services_Infrastructure_in_7_Days/index.txt
- site/content/events/2016-kiel/proposals/Coping_with_Continuous_Delivery/index.txt
- site/content/events/2016-kiel/proposals/Going_DevOps/index.txt
- site/content/events/2016-kiel/proposals/Militarise_Enterprise_IT/index.txt
Hi,
please merge changes
thank you,
Maik
> added more talks

- site/content/events/2016-kiel/proposals/Fury_and_Love/index.txt
- site/content/events/2016-kiel/proposals/Lessons_learnt/index.txt
- site/content/events/2016-kiel/proposals/Scalable_and_clean_build_environments/index.txt
Hi,
Thank you very much for adding the changes always so quickly.
Cheers,
Maik
> more and more talks

- site/content/events/2016-kiel/proposals/DevOpsAtScale/index.txt
- site/content/events/2016-kiel/proposals/Docker_Container_Lifecycles/index.txt
- site/content/events/2016-kiel/proposals/Docker_in_production/index.txt
- site/content/events/2016-kiel/proposals/Prerequisites_for_DevOps/index.txt
- site/content/events/2016-kiel/proposals/Scalable_and_clean_build_environments/index.txt
- site/content/events/2016-kiel/proposals/The_Challenges_of_Adopting_DevOps/index.txt
- site/content/events/2016-kiel/proposals/Thefuture_of_testing_how_testers_improves/index.txt
> many more proposals

- site/content/events/2016-newzealand/_team_local.txt
> Adding new organizer.

- site/content/events/2016-minneapolis/proposals/Continuous Testing in a DevOps World/index.txt
- site/content/events/2016-minneapolis/proposals/Deployment Scripts Are Dead Meet Rultor/index.txt
- site/content/events/2016-minneapolis/proposals/Orchestration APIs/index.txt
- site/content/events/2016-minneapolis/proposals/The Self-Designing Organization/index.txt
> Adding new talks to MSP.

- site/content/_future.txt
- site/content/events/2016-losangeles/_event_date_end.txt
- site/content/events/2016-losangeles/_event_date_start.txt
- site/content/events/2016-losangeles/_menu.txt
- site/content/events/2016-losangeles/index.html
Taking Los Angeles off the site, per @ubergeekgirl. Their planning is now paused.
> Taking Los Angeles off the site.

- site/content/events/2016-kiel/proposals/Automation with Ansible/index.txt
- site/content/events/2016-kiel/proposals/Collect_all_the things_with_Beats/index.txt
- site/content/events/2016-kiel/proposals/Introducing_A_DevOps_Culture/index.txt
- site/content/events/2016-kiel/proposals/The_UnSurprising_Truth/index.txt
Hi,
please merge the last minute proposals.
thank you,
Maik
> last minute proposals

- site/content/events/2016-kiel/index.html
- site/content/events/2016-kiel/proposals/ITIL_and_DevOps/index.txt
> added proposal and changed welcome page

- site/content/events/2016-vancouver/index.html
> YVR fix IRC link

- site/content/events/2016-atlanta/_team_local.txt
ATL organizer update per Tom Hall.
> ATL organizer update

- site/content/events/2016-istanbul/_team_local.txt
Adding Istanbul organizers per Rommel Tinoco.
> Adding Istanbul organizers

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
(and re-ordering the front page)
> Updating ATL's date

- site/content/events/2016-minneapolis/location/index.html
- site/content/events/2016-minneapolis/propose/index.html
Making explicit what we are already doing.
> Accessibility & affordability notes.

- site/content/events/2016-minneapolis/registration/index.html
Early-bird pricing for non-profit, startup, and self-financed; options for cases where cost is still prohibitive.
> Discounts for cases of need.

- site/content/events/2016-minneapolis/proposals/Changing the Game at Optum/index.txt
- site/content/events/2016-minneapolis/proposals/Marketing: the devops comrades you didn't know you had/index.txt
> New talks for MSP.

- site/content/events/2016-saltlakecity/_cfp_date_announce.txt
- site/content/events/2016-saltlakecity/_cfp_date_end.txt
- site/content/events/2016-saltlakecity/_sponsors.txt
> [SLC2016] Adding new sponsors: Pivotal and ArrestedDevOps

- site/content/events/2016-amsterdam/_menu.txt
- site/content/events/2016-amsterdam/location/index.html
- site/content/events/2016-amsterdam/propose/index.html
:tada: [Celebrate!](https://www.youtube.com/watch?v=UWLIgjB9gGw) :tada:
> CFP opened + location added

- site/content/events/2016-portland/index.html
Also cleaned up the mass of empty <br><br> blocks by moving some comment
characters around.
> Adding an announcements email list

- site/content/events/2016-washington-dc/_cfp_date_end.txt
- site/content/events/2016-washington-dc/_cfp_date_start.txt
- site/content/events/2016-washington-dc/_menu.txt
- site/content/events/2016-washington-dc/index.html
- site/content/events/2016-washington-dc/sponsor/index.html
> We are ready to open up DevOpsDays DC 2016

- site/content/events/2016-kiel/proposals/War_Games/index.txt
> one more proposal

- site/content/events/2016-atlanta/_team_local.txt
> Adding organizers.

- site/content/events/2016-minneapolis/proposals/The Banality of Effectiveness/index.txt
> Adding new talk for MSP.

- site/content/events/2016-amsterdam/_target_date.txt
> There is no 31st of June.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/events/2016-istanbul/_menu.txt
- site/content/events/2016-istanbul/_target_date.txt
- site/content/events/2016-istanbul/index.html
- site/content/events/2016-istanbul/location/index.html
- site/content/js/googlemaps_content.js
Announcing Istanbul's dates, per Erkan Binici.
> Announcing Istanbul's dates.

- site/content/events/2016-london/program/index.html
Michael Coté and Casey West needed their names fixed. /cc @kramos
> Name fixes

- site/content/events/2016-minneapolis/proposals/Being an introvert and at a conference, not as hellish as you think it is/index.txt
- site/content/events/2016-minneapolis/proposals/I'm a text editor and so can you/index.txt
- site/content/events/2016-minneapolis/proposals/Lets verify your OpenStack cloud's level of Security/index.txt
> New talks for MSP

- site/content/events/2016-amsterdam/sponsor/index.html
https://www.youtube.com/watch?v=cpbbuaIA3Ds
> Sponsor information added to Amsterdam event

- site/content/events/2016-kiel/_cfp_date_announce.txt
- site/content/events/2016-kiel/_menu.txt
- site/content/events/2016-kiel/program/index.html
- site/content/events/2016-kiel/propose/index.html
> added first confirmed speakers

- site/content/events/2016-kiel/program/index.html
- site/content/events/2016-kiel/proposals/War_Games/index.txt
> more confirmed speakers

- site/content/_future.txt
- site/content/_past.txt
- site/content/js/googlemaps_content.js
- site/layouts/default.txt
> Front-page cleanup.

- site/content/events/2016-newzealand/_team_local.txt
Added organizer for New Zealand.
> Added organizer for New Zealand.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/events/2016-newyork/_email_organizers.txt
- site/content/events/2016-newyork/_menu.txt
- site/content/events/2016-newyork/_sponsors.txt
- site/content/events/2016-newyork/_team_local.txt
- site/content/events/2016-newyork/code-of-conduct/index.html
- site/content/events/2016-newyork/contact/index.html
- site/content/events/2016-newyork/index.html
- site/content/events/2016-newyork/location/index.html
- site/content/events/2016-newyork/program/index.html
- site/content/events/2016-newyork/propose/index.html
- site/content/events/2016-newyork/registration/index.html
- site/content/events/2016-newyork/sponsor/index.html
- site/content/js/googlemaps_content.js
Corrections to the front page to add NYC and to the NYC pages to make them render.
> NYC corrections

- site/content/events/2016-istanbul/_cfp_date_announce.txt
- site/content/events/2016-istanbul/_cfp_date_end.txt
- site/content/events/2016-istanbul/_cfp_date_start.txt
- site/content/events/2016-istanbul/_menu.txt
- site/content/events/2016-istanbul/index.html
> CFP dates for Istanbul.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/events/2016-detroit/_event_date_end.txt
- site/content/events/2016-detroit/_event_date_start.txt
- site/content/js/googlemaps_content.js
Detroit still needs to sign their venue.
> Detroit still needs to sign their venue.

- site/content/events/2016-kiel/_menu.txt
- site/content/events/2016-kiel/index.html
- site/content/events/2016-kiel/program/index.html
> program is ready!

- site/content/events/2016-minneapolis/_sponsors.txt
> Fix appdynamics image URL

- site/content/events/2016-kiel/program/index.html
> program changes

- site/content/js/googlemaps_content.js
Silicon Valley link correction.
> Silicon Valley link correction.

- site/content/events/2016-raleigh/_team_local.txt
Correcting Raleigh's organizer list.
> Correcting Raleigh's organizer list.

- site/content/events/2016-nashville/_team_local.txt
> Adding Nashville organizer

- site/content/events/2016-amsterdam/registration/index.html
Temporarily hide registration page as it is not fully ready for primetime
> updates registration page for AMS 2016

- site/content/events/2016-amsterdam/registration/index.html
> re-adds registration form

- site/content/events/2016-philadelphia/_menu.txt
- site/content/events/2016-philadelphia/index.html
- site/content/events/2016-philadelphia/registration/index.html
> Adding reg for Philly

- site/content/events/2016-madison/_team_local.txt
> Add Cea Stapleton as an organizer for 2016-madison.

- site/content/events/2016-singapore/_menu.txt
- site/content/events/2016-singapore/index.html
- site/content/events/2016-singapore/propose/index.html
- site/content/events/2016-singapore/sponsor/index.html
- add link to CfP form 
- enable link to 'propose'
- reviewed sponsor text
> SIN-16 Update sponsor & CfP details

- site/content/events/2016-istanbul/sponsor/index.html
> Istanbul sponsorship info.

- site/content/events/2016-raleigh/_team_local.txt
> Removing Raleigh organizer.

- site/content/events/2016-philadelphia/_sponsors.txt
Pivotal sponsorship - per @peterjshan.
> Pivotal sponsorship

- site/content/events/2016-london/_menu.txt
- site/content/events/2016-london/hackathon/index.html
- site/content/events/2016-london/index.html
Signed-off-by: kramos <markosrendell@gmail.com>
> Adding hackathon page and writing SOLD OUT

- site/content/events/2016-portland/_menu.txt
- site/content/events/2016-portland/registration/index.html
People will probably buy tickets faster if we link them to it, right?
> Adding registration link for PDX 2016

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
Adding Boise with dates to front page.
> Adding Boise with dates to front page.

- site/content/events/2016-boise/_event_date_end.txt
- site/content/events/2016-boise/_event_date_start.txt
- site/content/events/2016-boise/_target_date.txt
- site/content/events/2016-boise/_team_local.txt
- site/content/events/2016-boise/index.html
- site/content/events/2016-boise/location/index.html
Reverts jedi4ever/devopsdays-webby#2605
Venue contract still in progress.
> Revert "Updating Boise info"

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
Reverts jedi4ever/devopsdays-webby#2607
Venue contract still in progress.
> Revert "Adding Boise with dates to front page."

- site/content/events/2015-detroit/proposals/agility-without-fragility/index.txt
- site/content/events/2015-detroit/proposals/automate-aws/index.txt
- site/content/events/2015-detroit/proposals/cd-decision-points/index.txt
- site/content/events/2015-detroit/proposals/cloud-anti-patterns/index.txt
- site/content/events/2015-detroit/proposals/five-love-languages/index.txt
- site/content/events/2015-detroit/proposals/how-to-devops-poorly/index.txt
- site/content/events/2015-detroit/proposals/how-to-train-yourself/index.txt
- site/content/events/2015-detroit/proposals/hugops/index.txt
- site/content/events/2015-detroit/proposals/human-load-balancing/index.txt
- site/content/events/2015-detroit/proposals/land-of-the-living-donkeys/index.txt
- site/content/events/2015-detroit/proposals/opportunity-devops/index.txt
- site/content/events/2015-detroit/proposals/our-child-devops/index.txt
- site/content/events/2015-detroit/proposals/pipeline-patterns/index.txt
- site/content/events/2015-detroit/proposals/securing-software-development/index.txt
- site/content/events/2015-detroit/proposals/there-and-back-again/index.txt
- site/content/events/2015-detroit/proposals/why-analytics-fail/index.txt
Embedded youtube vids for all the 2015 Detroit talks
> Add video links for Detroit 2015

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
> Boston for front page

- site/content/events/2016-amsterdam/_team_local.txt
> Additional AMS team member

- site/content/events/2016-minneapolis/_sponsors.txt
Changing "Media Sponsor" to "Community Partner".
> Changing "Media Sponsor" to "Community Partner".

- site/content/events/2016-madison/index.html
Added a iframe to display a Show of interest google form.
> Add google form for Madison 2016

- site/content/events/2016-minneapolis/_menu.txt
- site/content/events/2016-minneapolis/index.html
- site/content/events/2016-minneapolis/propose/index.html
> Closing CFP.

- site/content/events/2016-vancouver/_menu.txt
- site/content/events/2016-vancouver/program/index.html
- site/content/events/2016-vancouver/proposals/Gender_in_organizations_From_fixing_the_women_to_liberating_the_men/index.txt
* Remove proposals page from menu
* Update program and add program page to menu
> Vancouver 2016 - Create program

- site/content/events/2016-vancouver/program/index.html
> Vancouver 2016 - Update programm

- site/content/events/2016-oslo/_team_local.txt
> Adding new Oslo organizer.

- site/content/events/2016-vancouver/sponsor/index.html
* Add section for five minute demo
> Vancouver 2016 - Update sponsor FAQ

- site/content/events/2016-minneapolis/_menu.txt
- site/content/events/2016-minneapolis/index.html
- site/content/events/2016-minneapolis/program/allanespinosa/index.html
- site/content/events/2016-minneapolis/program/benzvan/index.html
- site/content/events/2016-minneapolis/program/charitymajors/index.html
- site/content/events/2016-minneapolis/program/index.html
- site/content/events/2016-minneapolis/program/jamieriedesel/index.html
- site/content/events/2016-minneapolis/program/jeffsmith/index.html
- site/content/events/2016-minneapolis/program/megancarney/index.html
- site/content/events/2016-minneapolis/program/nicoleforsgren/index.html
- site/content/events/2016-minneapolis/program/sarahgoffdupont/index.html
- site/content/events/2016-minneapolis/propose/index.html
Adding 30-min talks to Minneapolis 2016.
> Adding 30-min talks to Minneapolis 2016.

- site/content/events/2016-minneapolis/program/charitymajors/index.html
> Talk edits

- site/content/events/2016-minneapolis/program/index.html
> Dammit, webby.

- site/content/events/2016-boise/_event_date_end.txt
- site/content/events/2016-boise/_event_date_start.txt
- site/content/events/2016-boise/_target_date.txt
- site/content/events/2016-boise/_team_local.txt
- site/content/events/2016-boise/index.html
- site/content/events/2016-boise/location/index.html
Reverts jedi4ever/devopsdays-webby#2609
Their contract is signed.
> Revert "Revert "Updating Boise info""

- site/content/events/2016-newyork/_menu.txt
Thanks to @iennae for noticing that it was missing!
> Adding NYC location link to menu.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/events/2016-boise/_menu.txt
- site/content/js/googlemaps_content.js
Thanks to @iennae for the reminder!
> Boise dates on front page.

- site/content/events/2016-seattle/location/index.html
our hotel is sold out so listing some options for people
> added some hotel options

- site/content/events/2016-philadelphia/_team_local.txt
Adding new Philly organizer. /cc @peterjshan
> Adding new Philly organizer.

- site/content/events/2016-london/program/index.html
> Swapping the days of John Clapham for Simon Van Colina's ignites.

- site/content/events/2016-minneapolis/location/index.html
> Clarified hotel availability.

- site/content/events/2016-vancouver/conduct/index.html
- site/content/events/2016-vancouver/program/index.html
* Add ignites to the program
* Update Code of Conduct contact inforamtion
> Vancouver 2016 - CoC and program update

- site/content/events/2016-kiel/program/index.html
Hi,
Please merge changes.
thank you.
Maik
> program change

- site/content/events/2015-pittsburgh/index.html
- site/content/events/2015-pittsburgh/propose/index.html
Anything else we should add, @sethvargo @meatballhat @j41manning @cmluciano?
> Updates Pittsburgh 2015 with video links, etc.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/events/2016-kansascity/location/index.html
- site/content/js/googlemaps_content.js
> Kansas city front page

- site/content/events/2016-vancouver/program/index.html
- site/content/events/2016-vancouver/proposals/So_You_Want_to_Choose_a_new_CI_Tool_without_being_a_dictator/index.txt
* Update program
* Change proposal from talk to ignite
> Vancouver 2016 - Update program

- site/content/events/2016-kansascity/_sponsors.txt
adding gold and silver sponsors to kick things off
> adding sponsors

- site/content/events/2016-vancouver/location/index.html
> Vancouver 2016 - Update location page

- site/content/events/2015-boston/program/index.html
> 2015-boston: add daily videos

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
> Moving Vancouver to past.

- site/content/events/2016-singapore/_team_local.txt
> SIN-16 team: Add names for local team

- site/content/events/2016-london/program/index.html
Signed-off-by: kramos <markosrendell@gmail.com>
> Adding link to Bridget's slides

- site/content/events/2016-newyork/_team_local.txt
Adding NYC organizer per Peter Norton.
> Adding NYC organizer.

- site/content/events/2016-capetown/_team_local.txt
Adding Cape Town organizer per Tom Bamford.
> Adding Cape Town organizer

- site/content/_future.txt
- site/content/_past.txt
- site/content/_upcoming.txt
- site/content/js/googlemaps_content.js
Moving London, Denver, and Atlanta to past.
> Moving events to past.

- site/content/events/2016-amsterdam/_sponsors.txt
Show Chef as gold sponsor too.
Removed space to satisfy my OCD.
removed "become silver sponsor" as we have enough in the waiting list.
> [AMS-2016] A few sponsor changes

- site/content/events/2016-seattle/registration/index.html
This has been cancelled - was already removed from the Hugo site. Thought it was gone here too.
> removed hackathon
