- site/content/events/2015-austin/_team_global.txt
- site/content/events/2015-chicago/_team_global.txt
- site/content/events/2015-denver/_team_global.txt
- site/content/events/2015-derby/_team_global.txt
- site/content/events/2015-ljubljana/_team_global.txt
- site/content/events/2015-minneapolis/_team_global.txt
- site/content/events/2015-paris/_team_global.txt
- site/content/events/2015-washington-dc/_team_global.txt
Removed retired organizer and added missing organizer for Chicago (cc @LanyonM).
> Removed retired organizer.

- site/content/_future.txt
Just a placeholder until they get a chance to add it (by request).
> Adding per Jennifer Davis.

- site/content/events/2015-paris/program/index.html
Announcing John Willis opening keynote in our program.
cc @phrawzty , @jooooooon
> Paris 2015: announcing John Willis opening keynote

- site/content/events/calendar/index.html
- site/content/events/index.txt
I keep seeing discussions where people are trying to pick dates for their devopsdays and not being aware of other events in the same space which might affect their date selection. I'm attempting to alleviate that with this calendar (and I picked the URL to make it easy to remember/hand out).
Since this is a change to the site itself, it would be nice to have another core organizer review it (for concept/placement/idea - I've tested it technically).
> Added calendar of related events.

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/index.html
To prevent one event's flag from overlaying and completely covering another's. Also, putting events in the chronological order.
> Rearranged front-page map & ordered events.

- site/content/pages/organizing/05-After the Event/11-how-to-pay-us-back.txt
- site/content/pages/organizing/charity/index.txt
- site/content/pages/organizing/index.txt
Because of the autogeneration of the main organizing page we need to
exclude the charity dir.  But the only way I found was by excluding the
index.html page.  As all the other dirs do not have an index page
> Charity page and link to it added

- site/content/events/2015-washington-dc/_sponsors.txt
missed a comma in _sponsors.txt, which caused the entire DC site to be
replaced with the single word "true" - perhaps an edgy marketing
campaign but not really what we meant to do
> [URGENT dc 2015] brown paper bag typo

- Vagrantfile
- bootstrap.sh
Virtualbox and VMware are more widely deployed than Parallels, and are
the two "standard" Vagrant providers. This lowers barriers to entry
for people who want to use Vagrant to hack on the site.
* use the most recent Vagrantfile template
* use Chef's Ubuntu 12.04 box (supports both VB and VMW)
* add configuration for Virtualbox and VMware
* install curl in the bootstrap script, since Chef's box doesn't include it
> Modify Vagrantfile for better developer experience

- site/content/events/2015-amsterdam/program/index.html
I merged the changes from @drozer without checking that the dates were accurate. Doh!
This proposed change fixes the dates as @ksatirli requested on the organizer list, and removes the unlabeled workshops as he suggested. I'll merge this if it's what @ksatirli intends - @ksatirli?
We still haven't added "program" to the navigation bar, which is perhaps already known.
> Changes per Kerim.

- site/content/events/2015-paris/propose/index.html
We didn't had a way to propose ignite talks for Paris 2015, since we closed the CfP, let's add back the proposal e-mail address.
Please merge at your convenience.
Thanks!
> Paris 2015: we're still accepting ignite talks

- site/content/events/2015-amsterdam/_sponsors.txt
Because webby is very annoying. Fixed.
> Missing comma turns the whole AMS 2015 site to "true".

- README-Windows.md
The documentation had the FTP as port 2121 but in the VagrantFile it was 2021
Some of the bold headings didn't have a new line at the end.
> Bug - Fixed a typo in the port for FTP and some basic formatting

- site/content/events/2015-pittsburgh/registration/index.html
We'll go live with the link, but I have a support email out to Showclix about how to get a checkout widget back. The event id numbers are apparently not the same as the number used for the widget, so I can't just change it.
@cmluciano
@littleidea
@carsomyr
@meatballhat
@sethvargo
> Adds Pittsburgh 2015 registration link

- site/content/events/2015-pittsburgh/contact/index.html
and mentions Justin Reese and C&S for financial support.
> Fixes email language on Contact Us page for Pittsburgh 2015

- site/content/events/2015-pittsburgh/index.html
The old link should have been removed.
@bridgetkromhout: high priority, because oops.
**THIS IS THE CORRECT YEAR**
> Removes hotel link from Pittsburgh 2015

- site/content/events/2015-pittsburgh/propose/index.html
Markdown chokes on the newline at the end of the _email_proposals
file and munges the link. Switching to HTML fixes that.
> Fixes Ignite talk mailto link on Pittsburgh 2015 proposals

- site/content/events/2015-amsterdam/program/index.html
Workshops weren't showing in a nice way (aka. we have too many).
> [ams2015] Removed truncated abstracts.

- site/content/_future.txt
- site/content/_upcoming.txt
Moving Charlotte from "upcoming" to "future" because we put events in the legend above the map (and on the map) when a date is set. That's probably a bit ambiguous.
Also, I noticed this because an errant smartquote broke webby (yes, I know, webby is a pain) so the map was broken for the front page. Please use `webby autobuild` to check changes locally before submitting a PR. (cc @alfonso-cabrera @KrisBuytaert fyi)
> Moving Charlotte from "upcoming" to "future"

- site/content/_future.txt
- site/content/_past.txt
The blue box wasn't large enough, so some events at the bottom of 2014 were missing.
> Ensuring all events show up.

- site/content/_future.txt
There is a special quote char in Charlotte URL breaking Silicon Valley url on the site.
However, this Charlotte link is actually duplicate, so removing it solves two problems.
> Fix broken link for upcoming SV event

- site/content/_future.txt
- site/content/_upcoming.txt
- site/content/index.html
The front-page map needed some rearrangement so dates weren't blocking other dates.
Also, the "future" list needed to be more consistent, and the "upcoming" legend needed to be more evenly balanced.
> Front-page cleanup/adding Charlotte to map.

- site/content/events/2015-singapore/registration/index.html
This variable is needed to make hyperlinks work correctly.
Wonder if this can be set globally for each event.
> [SIN-15] registration: Set `eventhome` variable

- site/content/events/2015-singapore/sponsor/index.html
This allows visitors to buy the ticket right away.
We get a notification from ti.to and the donator also gets a reminder to
send us his logo.
Also cleaned up the 'Please contact us' links to display only a minimum.
> [SIN-15] sponsor: Add link to 'contributor' ticket

- site/content/events/2015-siliconvalley/proposals/Empathy is transferable: How to create a culture of empathy among a dev team for DevOps and Ops/index.txt
Here's why this one wasn't showing up:
[07:05:09] ERROR: <Webby::Resources::MetaFile::Error> corrupt meta-data (perhaps there is an errant YAML marker '---' in the file)
-- syntax error on line 11, col 39: `title: "title: "Empathy is transferable: How to create a culture of empathy among a dev team for DevOps and Ops"
This was an error introduced in https://github.com/jedi4ever/devopsdays-webby/pull/2087 - heads up to @pmoosh.
> Correction so talk can show up.

- site/content/pages/organizing/01-Getting started/03-website-and-email.txt
I'd like other core organizers to look at this PR, as I've clarified what I think has been the unwritten guidance around what we want people to call their devopsdays event and at what point of completion they can send their PR (I'm in favor of asap). I'm also explicitly inviting new organizers to Slack.
> Clarifications around website updates.

- site/content/js/googlemaps_content.js
It does not overlap other cities and is now easier to click
> Move the label for Seattle on the map

- site/content/events/2015-washington-dc/index.html
- site/content/events/2015-washington-dc/program/index.html
* Remove any links to e.devopsdaysdc.org
* Clean-up the home and program page a bit
> etherpad from DevOpsDays DC 2015 is no more

- site/content/events/2015-minneapolis/index.html
- site/content/events/2015-minneapolis/registration/index.html
- site/content/events/2015-minneapolis/sponsor/index.html
People think 2016 is sold out already because they are googling and getting 2015, so this should help with the confusion.
> Update Minneapolis 2015 pages to redirect to 2016.

- site/content/events/2016-boston/_target_location.txt
Heads up to @masteinhauser - this field makes this happen:
> Removing venue-specific info for now.

- site/content/events/2016-boston/propose/index.html
We aren't actually ready to announce our CFP, and certainly not with a wrong date of when it will close!
Just "commenting" this out for now, to revisit with the existing structure which I really like and want to use in our actual announce.
> 2016-boston: hide proposal content until announce

- site/content/events/2016-denver/_team_local.txt
Removing Denver organizer who stepped down.
CC @tavisto
> Removing Denver organizer who stepped down.

- site/content/events/2016-atlanta/index.html
I copied the link wrong last night. Whoops.
> fixing link to keynote description

- site/content/_twitterfeed.txt
This changes the tweetstream to use a list (and widget) from devopsdaysMSP instead of the old search one, which got a lot of spam.
Before:
After:
An improvement would be to make a definitive list under @devopsdays. I'd like to get this merged before Vancouver starts tomorrow so that when people are going to the site all day they won't be spammed.
Since it's a front-page change, I'd like at least one other Core team member to :+1: it.
> Changing tweetstream to whitelisted.

- site/content/_twitterfeed.txt
The default twitter widget can't have the height we used to use. I will see if there's CSS stuff to get around this (making the map taller doesn't look great) - meanwhile, 2 tweets instead of 3.
> Layout issue fix

- site/content/events/2016-boston/propose/index.html
Moved our CFP to papercall.io instead of via email. Forgot to actually update the website.
> 2016-boston: move cfp to papercall.io
